building: residential
lr: 1.0e-4
buffer_size: 10000
batch_size: 32
gamma: 0.99
epsilon_start: 1.0
epsilon_end: 0.05
epsilon_decay: 500
n_episodes: 2000
lambda_E: 1.0
lambda_C: 2.0
lambda_P: 0.5
target_update_freq: 10
